# Generated by Django 4.2.21 on 2025-05-25 22:57

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DatosDashboard",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("pais", models.CharField(max_length=50)),
                ("ciudad", models.CharField(max_length=100)),
                ("dia", models.IntegerField()),
                ("mes", models.CharField(max_length=50)),
                ("año", models.IntegerField()),
                ("marca", models.CharField(blank=True, max_length=100, null=True)),
                ("categoria", models.CharField(blank=True, max_length=100, null=True)),
                ("formato", models.CharField(blank=True, max_length=100, null=True)),
                ("sabor", models.CharField(blank=True, max_length=100, null=True)),
                ("ruta", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "distribuidor",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "neto",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=18, null=True
                    ),
                ),
                (
                    "arancel",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=18, null=True
                    ),
                ),
                (
                    "ila13",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=18, null=True
                    ),
                ),
                (
                    "bruto",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=18, null=True
                    ),
                ),
                (
                    "cajas",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=18, null=True
                    ),
                ),
                (
                    "monto",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=18, null=True
                    ),
                ),
                (
                    "litros",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=18, null=True
                    ),
                ),
                (
                    "bonificacion_diplay",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=18, null=True
                    ),
                ),
                (
                    "bonificacion_litros",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=18, null=True
                    ),
                ),
                (
                    "codigo_sucursal",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("cliente", models.CharField(blank=True, max_length=255, null=True)),
                ("rut", models.CharField(blank=True, max_length=20, null=True)),
                ("direccion", models.CharField(blank=True, max_length=255, null=True)),
                ("giro", models.CharField(blank=True, max_length=100, null=True)),
                ("vendedor", models.CharField(blank=True, max_length=100, null=True)),
                ("supervisor", models.CharField(blank=True, max_length=100, null=True)),
                ("canal", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "com_distribuidor",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=18, null=True
                    ),
                ),
                (
                    "com_vendedor",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=18, null=True
                    ),
                ),
                ("ultima_actualizacion_carga", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Dato del Dashboard",
                "verbose_name_plural": "Datos del Dashboard",
                "ordering": ["-año", "-mes", "-dia"],
            },
        ),
    ]
