# Generated by Django 4.2.21 on 2025-05-25 23:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("reportes", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="datosdashboard",
            options={
                "ordering": ["-fecha_dato"],
                "verbose_name": "Dato del Dashboard",
                "verbose_name_plural": "Datos del Dashboard",
            },
        ),
        migrations.AddField(
            model_name="datosdashboard",
            name="fecha_dato",
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
    ]
