# Generated by Django 4.2.21 on 2025-05-28 22:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("reportes", "0003_datosrechazos"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="datosdashboard",
            options={
                "ordering": ["-año", "-mes", "-dia"],
                "verbose_name": "Dato de Venta",
                "verbose_name_plural": "Datos de Ventas",
            },
        ),
        migrations.AlterModelOptions(
            name="datosrechazos",
            options={
                "ordering": ["-año", "-mes", "-dia"],
                "verbose_name": "Dato de Rechazo",
                "verbose_name_plural": "Datos de Rechazos",
            },
        ),
        migrations.RenameField(
            model_name="datosdashboard",
            old_name="supervisor",
            new_name="codigo_cliente",
        ),
        migrations.RenameField(
            model_name="datosdashboard",
            old_name="bonificacion_diplay",
            new_name="display",
        ),
        migrations.RenameField(
            model_name="datosdashboard",
            old_name="canal",
            new_name="estado",
        ),
        migrations.RenameField(
            model_name="datosrechazos",
            old_name="display_cajas",
            new_name="arancel",
        ),
        migrations.RenameField(
            model_name="datosrechazos",
            old_name="ruta_cliente",
            new_name="codigo_cliente",
        ),
        migrations.RemoveField(
            model_name="datosdashboard",
            name="bonificacion_litros",
        ),
        migrations.RemoveField(
            model_name="datosdashboard",
            name="cajas",
        ),
        migrations.RemoveField(
            model_name="datosdashboard",
            name="fecha_dato",
        ),
        migrations.RemoveField(
            model_name="datosdashboard",
            name="ultima_actualizacion_carga",
        ),
        migrations.RemoveField(
            model_name="datosrechazos",
            name="estado_documento",
        ),
        migrations.RemoveField(
            model_name="datosrechazos",
            name="fecha_dato",
        ),
        migrations.RemoveField(
            model_name="datosrechazos",
            name="ultima_actualizacion_carga",
        ),
        migrations.AddField(
            model_name="datosdashboard",
            name="factura",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="datosdashboard",
            name="fecha_carga",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name="datosdashboard",
            name="motivo",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="datosdashboard",
            name="sucursal",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="datosdashboard",
            name="tipo",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="datosrechazos",
            name="bruto",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=18, null=True
            ),
        ),
        migrations.AddField(
            model_name="datosrechazos",
            name="codigo_sucursal",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="datosrechazos",
            name="com_distribuidor",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=18, null=True
            ),
        ),
        migrations.AddField(
            model_name="datosrechazos",
            name="com_vendedor",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=18, null=True
            ),
        ),
        migrations.AddField(
            model_name="datosrechazos",
            name="display",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=18, null=True
            ),
        ),
        migrations.AddField(
            model_name="datosrechazos",
            name="estado",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="datosrechazos",
            name="factura",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="datosrechazos",
            name="fecha_carga",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name="datosrechazos",
            name="giro",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="datosrechazos",
            name="ila13",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=18, null=True
            ),
        ),
        migrations.AddField(
            model_name="datosrechazos",
            name="monto",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=18, null=True
            ),
        ),
        migrations.AddField(
            model_name="datosrechazos",
            name="motivo",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="datosrechazos",
            name="neto",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=18, null=True
            ),
        ),
        migrations.AddField(
            model_name="datosrechazos",
            name="rut",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="datosrechazos",
            name="ruta",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="datosrechazos",
            name="tipo",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="datosdashboard",
            name="año",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="datosdashboard",
            name="ciudad",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="datosdashboard",
            name="codigo_sucursal",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="datosdashboard",
            name="dia",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="datosdashboard",
            name="mes",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="datosdashboard",
            name="pais",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="datosrechazos",
            name="marca",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="datosrechazos",
            name="mes",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="datosrechazos",
            name="vendedor",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
